### ISSUE TITLE
AttributeError: module 'base64' has no attribute 'decodestring'

### ISSUE THREAD

**Issue by boredazfcuk** [icloud-photos-downloader/icloud_photos_downloader#353]
I've upgraded to Alpine Linux 3.14,, which uses Python 3.9 and now I'm seeing this error when trying to retrieve credentials from the keyring:
```
Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/icloudpd-1.7.2-py3.9.egg/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/usr/lib/python3.9/site-packages/icloudpd-1.7.2-py3.9.egg/icloudpd/authentication.py", line 29, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.9/site-packages/pyicloud_ipd/base.py", line 141, in __init__
    password = get_password_from_keyring(apple_id)
  File "/usr/lib/python3.9/site-packages/pyicloud_ipd/utils.py", line 35, in get_password_from_keyring
    result = keyring.get_password(
  File "/usr/lib/python3.9/site-packages/keyring/core.py", line 42, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/lib/python3.9/site-packages/keyrings/alt/file_base.py", line 74, in get_password
    password_encrypted = base64.decodestring(password_base64)
AttributeError: module 'base64' has no attribute 'decodestring'
```

## Steps to Reproduce
1. Save credentials to keyring
2. Upgrade to Python 3.9
3. Run iCloudPD

## Expected Behavior
Download files without crashing out

## Actual Behavior
Crashes and fails to download files

## Context
According to this: https://github.com/kurtmckee/feedparser/issues/201 the base64.decodestring function has been depreciated in Python 3.9

Thanks for taking the time to look at this.

**Comment by mrtolkien** [comment]
Same here.

We're at python 3.11 already. This function has been deprecated since python 3.1, a decade ago. I think it's time to move on.

**Comment by boredazfcuk** [comment]
I fixed the issue months ago by running this command in my Docker container after setting up iCloudPD:

```
sed -i -e 's/password_encrypted = base64.decodestring(password_base64)/password_encrypted = base64.decodebytes(password_base64)/' \
      -e 's/password_base64 = base64.encodestring(password_encrypted).decode()/password_base64 = base64.encodebytes(password_encrypted).decode()/' \
      "/usr/lib/python3.10/site-packages/keyrings/alt/file_base.py"
```

presumably it’s same fix for Python 3.11, just needs the path updating.

**Comment by mrtolkien** [comment]
I just used a script with `pyicloud` which at least is slightly more maintained. But I wish this CLI worked too, it's easier to use for `cron` jobs.

**Comment by boredazfcuk** [comment]
My Docker container has an option to exit after a single download run, so can us scheduled to run via cron.

**Comment by mrtolkien** [comment]
Re-posting here as there was a new release and this is still not fixed.

This is due to a buggy dependency with `pyicloud`:
https://github.com/icloud-photos-downloader/icloud_photos_downloader/blob/master/requirements.txt

This package is using `pyicloud` 0.10.2 which was released more than two years ago now. The dependency should be moved to `pyicloud` 1.0 which is the one actually supporting python versions newer than 3.5:
https://github.com/picklepete/pyicloud/pull/371

**Comment by AndreyNikiforov** [comment]
> Re-posting here as there was a new release and this is still not fixed.
> 

Can you be more specific, please? What release are you trying and what are the steps that are not working, so I can repro/troubleshoot?

> This is due to an outdated dependency with `pyicloud`: https://github.com/icloud-photos-downloader/icloud_photos_downloader/blob/master/requirements.txt
> 
> This package is using `pyicloud` 0.10.2 which was released more than two years ago now...

Where are you looking at release data (dates and versions)? Master icloudpd is referencing pyicloud_ipd git tag btw.

**Comment by AndreyNikiforov** [comment]
icloudpd >1.8.0 updated dependencies and fixed the issue
