### ISSUE TITLE
Failure adding password to system keyring

### ISSUE THREAD

**Issue by petebocken** [icloud-photos-downloader/icloud_photos_downloader#469]
I am trying to store my password in the system keyring `$ icloud --username jappleseed@apple.com`, however when I do this I receive the error message below:

```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.8/site-packages/keyring/backends/OS_X.py", line 83, in set_password
    raise Exception()
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/icloud", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.8/site-packages/pyicloud_ipd/cmdline.py", line 209, in main
    utils.store_password_in_keyring(username, password)
  File "/opt/homebrew/lib/python3.8/site-packages/pyicloud_ipd/utils.py", line 53, in store_password_in_keyring
    return keyring.set_password(
  File "/opt/homebrew/lib/python3.8/site-packages/keyring/core.py", line 48, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/opt/homebrew/lib/python3.8/site-packages/keyring/backends/OS_X.py", line 85, in set_password
    raise PasswordSetError("Can't store password in keychain")
keyring.errors.PasswordSetError: Can't store password in keychain
```

**Comment by petebocken** [comment]
I'm experiencing the same issue on my other Mac as well. Both were upgraded to macOS 12.6. Maybe this is the cause?

```
% python3.8 --version
Python 3.8.14
% pip3.8 --version
pip 22.2.2 from /opt/homebrew/lib/python3.8/site-packages/pip (python 3.8)
% icloudpd --version
icloudpd, version 1.7.2
```

**Comment by petebocken** [comment]
Another update. So the other Mac, which this has always worked one appears to still be working fine. I am trying to setup icloudpd on the second Mac. I just tried updating to python 3.9 and I get the same error when trying to save the password to the keyring.

I execute `icloud --username my@email.com`, it asks for the password I enter that in. I receive the Find My warning to allow the sign in, I allow that. I receive the 6 digit code, I say "Y" to save password in keyring and I get this.

```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/keyring/backends/OS_X.py", line 83, in set_password
    raise Exception()
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/icloud", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/pyicloud_ipd/cmdline.py", line 209, in main
    utils.store_password_in_keyring(username, password)
  File "/opt/homebrew/lib/python3.9/site-packages/pyicloud_ipd/utils.py", line 53, in store_password_in_keyring
    return keyring.set_password(
  File "/opt/homebrew/lib/python3.9/site-packages/keyring/core.py", line 48, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/opt/homebrew/lib/python3.9/site-packages/keyring/backends/OS_X.py", line 85, in set_password
    raise PasswordSetError("Can't store password in keychain")
keyring.errors.PasswordSetError: Can't store password in keychain
```

**Comment by petebocken** [comment]
@menkej have you experienced this issue? I'm at a complete loss to get icloudpd automatically running again.

I'll take back my last statement on the existing Mac that was working before. It is also not working. When the script runs, it is asking for the icloud password, so it's not reading the keychain anymore either.

I tried uninstalling icloudpd and all versions of python and only installing python3.8 and it still always comes back with the keychain error.

**Comment by boredazfcuk** [comment]
I have it running in a container with Python 3.10. 

I needed to fix the version of certain dependencies and change some of the code icloudpd code using sed, in my Dockerfile. You can prob get it working by replicating these changes I made in your environment:

https://github.com/boredazfcuk/docker-icloudpd/blob/master/Dockerfile

**Comment by petebocken** [comment]
> You can prob get it working by replicating these changes I made in your environment:
> 
> https://github.com/boredazfcuk/docker-icloudpd/blob/master/Dockerfile

Thanks. I also saw a similar post [here](https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/464#issuecomment-1229180009)

So I would just be running these 3 sed commands?

```
   sed -i 's/from collections import Callable/from collections.abc import Callable/' "/usr/lib/python3.10/site-packages/keyring/util/properties.py" && \
   sed -i -e 's/password_encrypted = base64.decodestring(password_base64)/password_encrypted = base64.decodebytes(password_base64)/' \
      -e 's/password_base64 = base64.encodestring(password_encrypted).decode()/password_base64 = base64.encodebytes(password_encrypted).decode()/' \
      "/usr/lib/python3.10/site-packages/keyrings/alt/file_base.py" && \
   sed -i 's/again in a few minutes/again later. This process may take hours./' "/usr/lib/python3.10/site-packages/pyicloud_ipd/services/photos.py" && \
```

When I try to run the first one, the prompt goes to `cmdand>` and appears to be requiring more info. I can just run each 3 commands individually just right in terminal, correct? What else do I need to type to complete the command?

**Comment by petebocken** [comment]
> I have it running in a Docker container with Python 3.10.
> 
> I needed to fix the version of certain dependencies and change some of the icloudpd code using sed, in my Dockerfile. You can prob get it working by replicating these changes I made in your environment:
> 
> https://github.com/boredazfcuk/docker-icloudpd/blob/master/Dockerfile

Also, I'm assuming this is just to get icloudpd to work with Python 3.10 or does this have something to do with macOS 12.6? Since that update broke icloudpd for me and the keyring.

Like I mentioned above, I already tried running icloudpd with Python 3.8 and 3.9 (both of which should be supported with icloudpd). I know I read 3.10 isn't working out-of-the-box with icloudpd. But since even those Python versions won't work, I figured it was just something that changed with macOS 12.6.

**Comment by boredazfcuk** [comment]
IIRC, icloudpd broke with Python 3.8. Fixing the version of tzlocal to v2.1 was required to get it working on 3.8.
```
# Fix tzlocal to 2.1 due to Python 3.8 being default in alpine 3.13.5+
ARG python_dependencies="pytz tzlocal==2.1 wheel"
```

Python 3.9 and 3.10 are fixed with:
```
sed -i 's/from collections import Callable/from collections.abc import Callable/' "/usr/lib/python3.10/site-packages/keyring/util/properties.py"
```
and
```
   sed -i -e 's/password_encrypted = base64.decodestring(password_base64)/password_encrypted = base64.decodebytes(password_base64)/' \
      -e 's/password_base64 = base64.encodestring(password_encrypted).decode()/password_base64 = base64.encodebytes(password_encrypted).decode()/' \
      "/usr/lib/python3.10/site-packages/keyrings/alt/file_base.py"
```
Please note, that you need to make sure that these files exist in those locations. I think Python stores stie packages in different locations on different mahines... I'm sure I've seen it in `/usr/local/lib` on some OSs.

**Comment by petebocken** [comment]
I updated the path names. First command errors and the second "keyrings" package doesn't exist. "keyrings" isn't a package name, not sure how to address that.

```
% sed -i 's/from collections import Callable/from collections.abc import Callable/' "/opt/homebrew/lib/python3.10/site-packages/keyring/util/properties.py"
sed: 1: "/opt/homebrew/lib/pytho ...": extra characters at the end of h command

% sed -i -e 's/password_encrypted = base64.decodestring(password_base64)/password_encrypted = base64.decodebytes(password_base64)/' \
-e 's/password_base64 = base64.encodestring(password_encrypted).decode()/password_base64 = base64.encodebytes(password_encrypted).decode()/' \
"/opt/homebrew/lib/python3.10/site-packages/keyrings/alt/file_base.py"
sed: -e: No such file or directory
```

**Comment by petebocken** [comment]
@boredazfcuk (or anyone) Are you on macOS 12.6? Can you try testing adding an iCloud account to the System Keyring (I'd do a different one just in case)?  I'm really curious if a fresh save to the keyring actually works for you on 12.6. I'm still convinced that it has something to do with 12.6. I have icloudpd setup to run daily from a script and the next day exactly after I updated to 12.6 it stopped working. And then on my second Mac (that was already updated to 12.6) also has the exact same error message when I try to save to keyring.

My script still works perfectly fine, however I have to either manually type the password in each time I run it or, as I've done as a workaround for now, just save the password in the script. This is of course not ideal.

**Comment by boredazfcuk** [comment]
Hi,

No, I don't run it on Mac. The OS inside my container is Alpine Linux.

```
sed -i -e 's/password_encrypted = base64.decodestring(password_base64)/password_encrypted = base64.decodebytes(password_base64)/' \
-e 's/password_base64 = base64.encodestring(password_encrypted).decode()/password_base64 = base64.encodebytes(password_encrypted).decode()/' \
"/opt/homebrew/lib/python3.10/site-packages/keyrings/alt/file_base.py"
sed: -e: No such file or directory
```

It can't find this file: `/opt/homebrew/lib/python3.10/site-packages/keyrings/alt/file_base.py` so it suggests the Python package isn't installed. I can't remember how it gets installed. It's a dependency of something but I can't remember what, anyway, you should be able to manually install it with:
```
pip install keyrings.alt
```

**Comment by petebocken** [comment]
I installed keyrings into python3.10 and still cannot run the two sed commands:

```
% sed -i 's/from collections import Callable/from collections.abc import Callable/' "/opt/homebrew/lib/python3.10/site-packages/keyring/util/properties.py"
sed: 1: "/opt/homebrew/lib/pytho ...": extra characters at the end of h command

% sed -i -e 's/password_encrypted = base64.decodestring(password_base64)/password_encrypted = base64.decodebytes(password_base64)/' \ -e 's/password_base64 = base64.encodestring(password_encrypted).decode()/password_base64 = base64.encodebytes(password_encrypted).decode()/' \ "/opt/homebrew/lib/python3.10/site-packages/keyrings/alt/file_base.py"
sed:  -e: No such file or directory
```

**Comment by boredazfcuk** [comment]
The first error is a Mac problem. Try this instead:

```
sed -i '' 's/from collections import Callable/from collections.abc import Callable/' "/opt/homebrew/lib/python3.10/site-packages/keyring/util/properties.py"
```

The bottom error is telling you that this file does not exist: `/opt/homebrew/lib/python3.10/site-packages/keyrings/alt/file_base.py`
You need to find that file before you edit it.

**Comment by petebocken** [comment]
K, now that one worked.  Still can't get the other one to work.

```
% sed -i -e 's/password_encrypted = base64.decodestring(password_base64)/password_encrypted = base64.decodebytes(password_base64)/' \
-e 's/password_base64 = base64.encodestring(password_encrypted).decode()/password_base64 = base64.encodebytes(password_encrypted).decode()/' \
"/opt/homebrew/lib/python3.10/site-packages/keyrings/alt/file_base.py"
sed: -e: No such file or directory

% pwd
/opt/homebrew/lib/python3.10/site-packages/keyrings/alt

% ls
Gnome.py        escape.py
Google.py       file.py
Windows.py      file_base.py
__init__.py     keyczar.py
__pycache__     multi.py
_win_crypto.py  pyfs.py
```

**Comment by boredazfcuk** [comment]
I think it’s treating the -e as a file name. Change the -i command to -i '' again

**Comment by petebocken** [comment]
Like this? Still says no such file.

```
% sed -i '' -e 's/password_encrypted = base64.decodestring(password_base64)/password_encrypted = base64.decodebytes(password_base64)/' \ -e 's/password_base64 = base64.encodestring(password_encrypted).decode()/password_base64 = base64.encodebytes(password_encrypted).decode()/' \ "/opt/homebrew/lib/python3.10/site-packages/keyrings/alt/file_base.py"
sed:  -e: No such file or directory
```

**Comment by boredazfcuk** [comment]
Maybe it doesn’t like multiple expression edits… try splitting it into singles:

sed -i '' -e 's/password_encrypted = base64.decodestring(password_base64)/password_encrypted = base64.decodebytes(password_base64)/'  "/usr/lib/python3.10/site-packages/keyrings/alt/file_base.py"

sed -i '' -e 's/password_base64 = base64.encodestring(password_encrypted).decode()/password_base64 = base64.encodebytes(password_encrypted).decode()/' "/usr/lib/python3.10/site-packages/keyrings/alt/file_base.py"

**Comment by petebocken** [comment]
That worked. But still can't save to keyring:

```
Save password in keyring?  [y/N]: yTraceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/keyring/backends/OS_X.py", line 83, in set_password
    raise Exception()
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/icloud", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/pyicloud_ipd/cmdline.py", line 209, in main
    utils.store_password_in_keyring(username, password)
  File "/opt/homebrew/lib/python3.10/site-packages/pyicloud_ipd/utils.py", line 53, in store_password_in_keyring
    return keyring.set_password(
  File "/opt/homebrew/lib/python3.10/site-packages/keyring/core.py", line 48, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/opt/homebrew/lib/python3.10/site-packages/keyring/backends/OS_X.py", line 85, in set_password
    raise PasswordSetError("Can't store password in keychain")
keyring.errors.PasswordSetError: Can't store password in keychain
```

**Comment by petebocken** [comment]
I tried uninstalling icloudpd and all versions of python I had installed (just 3.9 and 3.10).

Ran through these steps:

```
brew install python

pip3 install icloudpd

pip3 install keyrings.alt

sed -i '' 's/from collections import Callable/from collections.abc import Callable/' "/opt/homebrew/lib/python3.10/site-packages/keyring/util/properties.py"

sed -i '' -e 's/password_encrypted = base64.decodestring(password_base64)/password_encrypted = base64.decodebytes(password_base64)/' "/opt/homebrew/lib/python3.10/site-packages/keyrings/alt/file_base.py"

sed -i '' -e 's/password_base64 = base64.encodestring(password_encrypted).decode()/password_base64 = base64.encodebytes(password_encrypted).decode()/' "/opt/homebrew/lib/python3.10/site-packages/keyrings/alt/file_base.py"
```

Still the same...
```
% icloud --username my@appleid.com
Enter iCloud password for my@appleid.com:
Save password in keyring?  [y/N]: y
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/keyring/backends/OS_X.py", line 83, in set_password
    raise Exception()
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/icloud", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/pyicloud_ipd/cmdline.py", line 209, in main
    utils.store_password_in_keyring(username, password)
  File "/opt/homebrew/lib/python3.10/site-packages/pyicloud_ipd/utils.py", line 53, in store_password_in_keyring
    return keyring.set_password(
  File "/opt/homebrew/lib/python3.10/site-packages/keyring/core.py", line 48, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/opt/homebrew/lib/python3.10/site-packages/keyring/backends/OS_X.py", line 85, in set_password
    raise PasswordSetError("Can't store password in keychain")
keyring.errors.PasswordSetError: Can't store password in keychain
```

I ran a test by installing macOS 12.6 in a Parallels VM and ran through the same steps to get it all setup and sure enough it works!

So clearly there is just something hosed up with my setup that I just can't figure out.

**Comment by Jonnypleasehelp** [comment]
jpbsleepy@mac.com or me.com or iCloud.com

**Comment by petebocken** [comment]
> [jpbsleepy@mac.com](mailto:jpbsleepy@mac.com) or me.com or iCloud.com

??

**Comment by AndreyNikiforov** [comment]
@petebocken did you try latest versions of icloudpd yet? Dependencies had been updates, so keyring issues is expected to go away. Pls reopen if you still see error.

**Comment by petebocken** [comment]
> @petebocken did you try latest versions of icloudpd yet? Dependencies had been updates, so keyring issues is expected to go away. Pls reopen if you still see error.

Appears to still have issues:
```
% icloud --username my@appleid.com
Enter iCloud password for my@appleid.com:
Save password in keyring?  [y/N]: y
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/keyring/backends/macOS/__init__.py", line 40, in set_password
    api.set_generic_password(self.keychain, service, username, password)
  File "/opt/homebrew/lib/python3.10/site-packages/keyring/backends/macOS/api.py", line 162, in set_generic_password
    Error.raise_for_status(status)
  File "/opt/homebrew/lib/python3.10/site-packages/keyring/backends/macOS/api.py", line 115, in raise_for_status
    raise cls(status, "Unknown Error")
keyring.backends.macOS.api.Error: (-25308, 'Unknown Error')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/icloud", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/pyicloud_ipd/cmdline.py", line 209, in main
    utils.store_password_in_keyring(username, password)
  File "/opt/homebrew/lib/python3.10/site-packages/pyicloud_ipd/utils.py", line 53, in store_password_in_keyring
    return keyring.set_password(
  File "/opt/homebrew/lib/python3.10/site-packages/keyring/core.py", line 60, in set_password
    get_keyring().set_password(service_name, username, password)
  File "/opt/homebrew/lib/python3.10/site-packages/keyring/backends/chainer.py", line 56, in set_password
    return keyring.set_password(service, username, password)
  File "/opt/homebrew/lib/python3.10/site-packages/keyring/backends/macOS/__init__.py", line 44, in set_password
    raise PasswordSetError("Can't store password on keychain: " "{}".format(e))
keyring.errors.PasswordSetError: Can't store password on keychain: (-25308, 'Unknown Error')
```

**Comment by petebocken** [comment]
> @petebocken another option to try is to use binaries from github Release page. Since they have dependencies baked in, the behavior may be different.

I downloaded icloudpd-ex-1.12.0-macos-amd64 from the releases page and I was able to get a macOS prompt to save the password to the keychain. After that running the script works every time without a password!

So after that I decided to look at my script again (that uses source) and I install v1.12.0 on my MacBook to test and oddly enough it also prompted me with the macOS dialog to enter my password to save to the keychain. After some digging, I saw that my MacBook has python 3.11 and 3.10 just like my Mac mini (which normally runs the script) but the MacBook also has 3.9 installed and I confirmed that /opt/homebrew/icloud is pointed at python 3.9.

Going back over to my Mac mini, I did not have Python 3.9 installed. So after installed that and ran my script, it gave me the macOS prompt to save the password to keychain. I removed the hardcoded password from my script and now it runs just like before using the keychain.

I know I had tested with having Python 3.9 installed previously, so no idea why it would suddenly start working again now. Either way, I guess I'm back in business and using the keychain again!

**Comment by AndreyNikiforov** [comment]
@petebocken I am glad that the issue is resolved.

It may be obvious to you already:

- when you install `icloudpd` package with `pip`, you install source code. All dependent packages are installed by `pip` at the same time. `pip` decides if package needs to be installed or existing version on your system is okay. `python` and `pip` must be installed on the system before you can install `icloudpd` source package. Note that even though you executed `icloud` as a binary (`% icloud --username my@appleid.com` in your example), it is just a shortcut for executing your version of python with installed source code of `icloud.py` and your versions of dependent packages.
- when you download binary package from Github releases (or use docker image), source code is baked-in with python and all necessary dependencies. You can run that binary on a system with any version python or without python at all. If fact our docker images are just that - bare bone Alpine linux with these binaries added, nothing else.

I hope this explanation helps your reconciling behavior of the `icloud*` on your system.

**Comment by petebocken** [comment]
@AndreyNikiforov thanks for explaining this!

As long as the pip version is working (and even if the keychain stops working again) I would probably continue using that method since I am able to setup automated updating through cron and pip.

Since that isn't possible if you use the binaries, correct?

**Comment by AndreyNikiforov** [comment]
@petebocken 

> ... I would probably continue using that method since I am able to setup automated updating through cron and pip.
> 
> Since that isn't possible if you use the binaries, correct?

Binary distribution can be autoupdated in docker ecosystem only. We do not distribute binaries through platform-specific app stores, which would have automatic updates. We do not have self updates either. Would be interesting to know what versions are used in the wild...

Note that we have `--watch-with-interval` parameter that allows `icloudpd` to run continuously, removing the need for cron for synchronizing photos. You will need cron if you implemented app update mechanism with it though.

**Comment by AndreyNikiforov** [comment]
Added #603 for version notification. #190 - statistics
