### ISSUE TITLE
Downloader does not download the .HEVC or .MOV of livephotos

### ISSUE THREAD

**Issue by jkkn** [icloud-photos-downloader/icloud_photos_downloader#90]
Hi,

Thanks for a great script for downloading and synchronization of ones iCloud library.

I notice an unfortunate issue.
Lots of our photos are now "live photos" but these are only downloaded as .jpeg or .heic format so the live photo itself is lost.

Could you add support so it also downloads the .hevc / .mov files that belongs to?
They are shown at icloud.com so they must be there.

Best wishes,
Kristian

**Comment by ndbroadbent** [comment]
Hi @jkkn, yes I agree we should handle this! I also take a lot of live photos and would nice to back those up. There's a previous issue about this: #14

Back then I didn't have too much time to work on this project, and it would probably require some changes to the `pyicloud` library that we're using. Hopefully someone can help me develop this feature, or I might find some time to work on it in the future. But I'll keep this issue open now because it's definitely something we should support.

**Comment by ndbroadbent** [comment]
I should also mention I just did a lot of work on the project a few days ago, where I did a big rewrite and got it up to 100% test coverage. So I feel like I probably need a little break for a while. The other problem is that I don't really use it anymore, although I do enjoy helping other people back up their photos.

With that in mind, I'd like to try an experiment to [see if I can raise some money to tackle this feature, so I started a thing on gofundme](https://www.gofundme.com/live-photo-support-for-icloudpd). And of course, no pressure at all, and if someone else wants to tackle the feature and send a PR, that would be awesome!

**Comment by jkkn** [comment]
I will be happy to help and just started by a small amount of money. Do you think that $300 will help you get all the way with live photos? - should we spread this gofundme upon the pyicloud project as well?

**Comment by ndbroadbent** [comment]
Wow that's awesome, thanks very much! Yes that's definitely enough for me to add some support for live photos. I'm not too sure about the pyicloud project, but I'll also add a note about it to this project's README. Thanks again!

**Comment by ndbroadbent** [comment]
Hi @jkkn, thanks again for your support! I've just pushed version `1.2.0` with support for live photos. When you run the script, you should start seeing files like `IMG_7455.LIVE-original.MOV`. You can also download the resized videos with `--live-photo-size [original|medium|thumb]`. Please let me know if that works for you!

**Comment by ndbroadbent** [comment]
I will also take a look at the edited images / changed keyframes

**Comment by jkkn** [comment]
Seem to do the same thing (no live photos) except it seems it starts downloading all photos with and without the "-original" postfix now. A feature I really would like to have a way of disabling btw so the filename is not changed when it is "original".

Maybe you forgot to actually push changes to the pyicloud git-repository? - I see this is still 0.9.1:
https://github.com/ndbroadbent/pyicloud/blob/master/setup.py

**Comment by ndbroadbent** [comment]
Ah I am using a different branch on that repo (pyicloud-ipd). You might need to run “pip uninstall icloudpd” and then “pip install icloudpd” to make sure you are using the latest version.

And good idea about the filename change, it probably makes sense to always skip “original” and only append it for the “small” and “thumb” sizes

**Comment by jkkn** [comment]
After looking a bit more into it - the live photos are actually being downloaded now but with the ".HEIC" appendix and no "-original" since we are not hitting this bit of code:
filename = version['filename'].replace(
                        ".MOV", "-%s.MOV" % live_photo_size)

So I am getting the images in "xxx-original.heic" and the live-photo in "xxx.heic". Is this what it should do or should it be "xxx.heic" and "xxx.hevc" to (or xxx.mov) be more correct?

**Comment by ndbroadbent** [comment]
Oh I see! Sorry my phone was just recording life photos as MOV files. Will also add support for heic/hevc. I’m just not sure about the Live Photo video format, it might still be MOV instead of hevc. Will figure that out and try to get this working!

**Comment by jkkn** [comment]
Looking at how iCloud for Windows does naming. Name should probably for an image "IMG_xxxx" be:

For (JPEGS):
IMG_xxxx.jpg
IMG_xxxx.MOV
IMG_xxxx (Edited).jpg     (actually for some strange reason the space " " is not really there but it is for heic).

For (HEIC) - notice _HEVC.MOV postfix:
IMG_xxxx.HEIC
IMG_xxxx.jpg
IMG_xxxx_HEVC.MOV
IMG_xxxx (Editied).HEIC
IMG_xxxx (Editied).jpg    (for some reason the space " " is not really there for jpg).

Other .MOV and .PNG are just as-is of course - do not know if they appear in an (Edited) version as well.

**Comment by ndbroadbent** [comment]
Hi @jkkn, I've removed the `-original` from the filename (but am still adding it for `-medium` and `-thumb` sizes in case people want to download those as well.) I've also removed `.LIVE.` from the filename for live videos. And also adding `_HEVC.MOV` for live photos from HEIC images. Much better to be consistent with the naming from iCloud for Windows.

Please try out the latest version with these changes: `pip install icloudpd==1.3.1`

Hope that helps, and I'll try to figure out the `(Edited)` images soon!

**Comment by jkkn** [comment]
Hi @ndbroadbent - thanks for working on this. I am currently downloading photos (running as writing) - looks good. I am seeing some "already exists" even I started from an empty folder but actually I think I saw this bug before the live-photo feature support so I think it is unrelated.

a) Regarding the "(Edited)" I think this is the type "resJPEGFullRes" which is used. If you look at icloud.com if you want to download the Edited you must download the "compatible" version - they say so if clicking on the small arrow next to the download icon - so guess its simply the "resJPEGFullRes" version that appears for only some pictures in the response is the edited picture. Besides that maybe we also need "resVidFullRes" for similar?

b) BTW... do you need to add "resOriginalVidComplRes" to desiredKeys or is _list_query_gen not in use in this case?

**Comment by AndreyNikiforov** [comment]
Closing as stale. @jkkn feel free to reopen or open new one if latest version of icloudpd (1.6.1 as of writing) still causing issues
